-- migrations/migration_tutorial_v2.sql
-- Tables pour gérer les étapes du tutoriel de manière flexible

-- Table 1 : Configuration des étapes du tutoriel
CREATE TABLE IF NOT EXISTS tutorial_steps (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  step_number INT NOT NULL UNIQUE,
  step_name VARCHAR(255) NOT NULL UNIQUE,
  page_route VARCHAR(50),
  dom_selector VARCHAR(500),
  popup_position VARCHAR(20),
  popup_title VARCHAR(150),
  popup_text TEXT,
  action_required VARCHAR(255),
  validator_logic VARCHAR(255),
  highlight_type VARCHAR(50),
  skip_allowed BOOLEAN DEFAULT true,
  display_duration_ms INT DEFAULT 0,
  is_mandatory BOOLEAN DEFAULT false,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table 2 : Progression du tutoriel par utilisateur
CREATE TABLE IF NOT EXISTS tutorial_progress (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  current_step INT DEFAULT 1,
  completed_steps INT[] DEFAULT ARRAY[]::INT[],
  tutorial_done BOOLEAN DEFAULT false,
  tutorial_skipped BOOLEAN DEFAULT false,
  last_step_viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Index pour les recherches courantes
CREATE INDEX idx_tutorial_steps_step_number ON tutorial_steps(step_number);
CREATE INDEX idx_tutorial_steps_page_route ON tutorial_steps(page_route);
CREATE INDEX idx_tutorial_progress_user_id ON tutorial_progress(user_id);
CREATE INDEX idx_tutorial_progress_done ON tutorial_progress(tutorial_done);

-- RLS : tutorial_steps = publique lecture seule
ALTER TABLE tutorial_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tutorial_steps_select_public" ON tutorial_steps
  FOR SELECT TO authenticated USING (true);

-- RLS : seul admin peut modifier tutorial_steps
CREATE POLICY "tutorial_steps_insert_admin" ON tutorial_steps
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS(SELECT 1 FROM users u WHERE u.id = auth.uid() AND u.is_admin = true)
  );
CREATE POLICY "tutorial_steps_update_admin" ON tutorial_steps
  FOR UPDATE TO authenticated
  USING (
    EXISTS(SELECT 1 FROM users u WHERE u.id = auth.uid() AND u.is_admin = true)
  );
CREATE POLICY "tutorial_steps_delete_admin" ON tutorial_steps
  FOR DELETE TO authenticated
  USING (
    EXISTS(SELECT 1 FROM users u WHERE u.id = auth.uid() AND u.is_admin = true)
  );

-- RLS : tutorial_progress = lecture/écriture propre user uniquement
ALTER TABLE tutorial_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tutorial_progress_select_own" ON tutorial_progress
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "tutorial_progress_insert_own" ON tutorial_progress
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "tutorial_progress_update_own" ON tutorial_progress
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "tutorial_progress_read_all_admin" ON tutorial_progress
  FOR SELECT TO authenticated
  USING (
    EXISTS(SELECT 1 FROM users u WHERE u.id = auth.uid() AND u.is_admin = true)
  );
